### ISSUE TITLE
safari兼容

### ISSUE THREAD

**Issue by ideaglon** [uxcore/uxcore-formatter#9]
ctx.fn.formatter('date', '2018-02-05 02:00:00', 'YYYY-MM-DD')   在safari下有问题

**Comment by eternalsky** [comment]
2018-02-05 02:00:00, 这种字符串本来 safari 就是不认的，formater 里没有引入 moment 去做这块的处理。

**Comment by ideaglon** [comment]
是否计划做兼容吗？

**Comment by eternalsky** [comment]
没有，这个库尽量会做的轻一些，请使用 timestamp 的格式传入进去。
